pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven { url 'https://maven.shedaniel.me/' }
		maven { url 'https://maven.terraformersmc.com/releases/' }
		mavenCentral()
		gradlePluginPortal()
	}
}

// Should match your modid
rootProject.name = 'vram-tweak'
